name: rentors
description: A new Flutter application.

# The following line prevents the package from being accidentally published torentors
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  card_swiper: ^1.0.4
  intl: ^0.17.0
  html: ^0.15.0
  flutter_html: ^2.1.5
  flutter_svg: ^0.23.0+1

  url_launcher: ^6.0.13
  http: ^0.13.3
  equatable: ^2.0.3
  global_configuration: 2.0.0-nullsafety.1
  dio: ^4.0.3
  flutter_bloc: ^7.3.3
  rflutter_alert: ^2.0.4

  pretty_dio_logger: ^1.1.1
  lottie: ^1.2.1
  timeago: ^3.1.0
  maps_launcher: ^2.0.1
  fluttertoast: ^8.0.8
  smooth_star_rating_null_safety: ^1.0.4+2
  country_code_picker: ^2.0.2
  carousel_slider: ^4.0.0
  flutter_secure_storage: ^5.0.2
  email_validator: ^2.0.1
  flutter_inappwebview: ^5.3.2
  rxdart: ^0.27.1
  image_picker: ^0.8.4+4
  date_format: ^2.0.4
  jiffy: ^4.1.0
  firebase_core: ^1.10.0
  firebase_auth: ^3.3.8
  firebase_messaging: ^11.1.0
  optimized_cached_image: ^3.0.0
  stripe_payment: ^1.1.4
  flutterwave: ^1.0.1
  razorpay_flutter: ^1.2.7
  credit_card_input_form: ^2.3.0

  flutter_local_notifications: ^9.1.2
  shimmer: ^2.0.0
  animations: ^2.0.2
  firebase_crashlytics: ^2.3.0
  google_sign_in: ^5.2.1
  marquee: ^2.2.0
  expandable_text: ^2.2.0
  google_maps_flutter: ^2.1.0
  google_place: ^0.4.3
  geolocator: ^7.7.1
  shared_preferences: ^2.0.8
  flutter_facebook_auth: ^3.5.6
  flutter_signin_button: ^2.0.0
  google_mobile_ads: ^1.0.0
  geocoder: ^0.2.1
  location: ^4.2.0
  android_intent: ^2.0.2
  permission_handler: ^9.2.0
  flutter_rating_bar: ^4.0.1

  crypto: ^3.0.0
  sign_in_with_apple: ^2.5.2
  device_info: ^2.0.3

dependency_overrides:
  provider: ^6.0.0




dev_dependencies:
  flutter_launcher_icons: ^0.9.1
  flutter_native_splash: ^1.2.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/ic_launcher.png"

flutter_native_splash:
  color: "#FFFFFF"  # required parameter
  image: assets/img/splash/splash.png  # optional parameter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/cfg/
    - assets/img/house.svg
    - assets/img/frame.svg
    - assets/img/facebook.svg
    - assets/img/heart.svg
    - assets/img/twitter.svg
    - assets/img/whatsapp.svg
    - assets/img/agreement.svg
    - assets/img/law.svg
    - assets/img/intro2.svg
    - assets/img/intro1.svg
    - assets/img/law.svg
    - assets/img/upload_second.svg
    - assets/img/upload.json
    - assets/img/flutterwave.png
    - assets/img/stripe.png
    - assets/img/razorpay.png
    - assets/img/ic_launcher_round.png
    - assets/img/splash/splash.png
    - assets/img/splash/logo.png
    - assets/img/splash/intro_1_home.webp
    - assets/img/splash/intro_2_home.webp
    - assets/img/splash/intro_3_home.webp
    - assets/img/splash/signin_background.jpeg
    - assets/img/search.svg
    - assets/img/location.svg
    - assets/img/green-star.svg
    - assets/img/drawer/account.svg
    - assets/img/drawer/category.svg
    - assets/img/drawer/chat.svg
    - assets/img/drawer/help.svg
    - assets/img/drawer/history.svg
    - assets/img/drawer/home.svg
    - assets/img/drawer/house(1).svg
    - assets/img/drawer/house(2).svg
    - assets/img/drawer/house.svg
    - assets/img/drawer/logout.svg
    - assets/img/drawer/noti.svg
    - assets/img/drawer/post_request.svg
    - assets/img/drawer/rent_item.svg
    - assets/img/drawer/settings.svg
    - assets/img/drawer/settings2.svg
    - assets/img/drawer/wishlist.svg
    - assets/img/menu-bg.png
    - assets/img/google.png
    - assets/img/facebook.png
    - assets/img/filter.png
    - assets/img/avatar.png
    - assets/img/location_marker.png
    - assets/img/pick_marker.png
    - assets/img/apple_logo.png
    - assets/network.json
    - assets/nodata.json
    - assets/loading.json


  fonts:
    - family: open
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 100
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 200
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 800

    # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
